services:
   _defaults:
      autoconfigure: true
      autowire: true

   Cgoit\ContaoFolderGalleryBundle\:
      resource: ../src
      exclude: ../src/{ContaoManager,DependencyInjection,CgoitFolderGalleryBundle.php}
