services:
   _defaults:
      autoconfigure: true
      autowire: true

   Cgoit\ContaoFolderGalleryBundle\:
      resource: ../src
      exclude: ../src/{ContaoManager,DependencyInjection,CgoitFolderGalleryBundle.php}

   Cgoit\ContaoFolderGalleryBundle\Provider\GalleryFolderProviderInterface:
      alias: Cgoit\ContaoFolderGalleryBundle\Provider\GalleryFolderProvider
      public: true

   Cgoit\ContaoFolderGalleryBundle\Metadata\GalleryMetadataManager:
      public: true
